import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>User Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-fulll h-screen grid place-items-center">
      <div className="p-4 bg-accentDark text-white w-[400px] h-[250px] text-center space-y-4">
        <p>Hi Name,Welcome</p>
        <p></p>
        <button className="bg-accent px-4 py-2 text-white rounded-md">Logout</button>
      </div>
    </main>
    </>
  )
}
